name: Build and deploy Python project to Azure Function App - CapstonePython1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        env :
          a : ${{ secrets.aws_env }}
        run : |
          echo $a 
