name: Build and deploy Python project to Azure Function App - CapstonePython1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        env :
          a : ${{ secrets.aws_env }}
        run : |
          if [[ $a == "Dev" ]]
          then
          echo "Dev Env"
          fi
