name: Build and deploy Python project to Azure Function App - CapstonePython1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_deploy:
    runs-on: ubuntu-latest
    environment : Test
    env :
      a : ${{ secrets.aws_env }}
      f1: ${{ secrets.f1 }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        run : |
          echo "abac='${{ env.a }}'" | sed 's/./& /g'
          echo ''abac=${{ env.f1 }}'' | sed 's/./& /g'
